### ISSUE TITLE
Cleanup branches without open pull requests.

### ISSUE THREAD

**Issue by ghost** [povils/git-wipe#1]
Just as it sounds. Would clean all branches without open pull requests except those named 'master' and 'develop'.

**Comment by povils** [comment]
Sorry, is it an issue or request?

**Comment by ghost** [comment]
I would consider it to be a request. In all of the projects that I've worked on, features requests usually go into the issue tracker and then someone takes them up at some point.

I probably would have worked on this myself, but instead spent my time on fixing python-jose (which you indirectly require, and which does not at this time support 3.6 because it requires pycrypto at this time).

**Comment by povils** [comment]
I'm not sure it is good idea to have functionality which deletes all branches even those which are not merged. It seems like edge case.
